pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                    echo "projectDir = MESBEService"

                '''
            }

        }

        stage('Pull from git') {
            steps {
                checkout scm

                sh "$PWD"
                dir('$projectDir') {
                    sh "$PWD"
                }
                sh "$PWD"
            }

        }

        stage('Build') {
            steps {
                //sh 'cd $projectDir'
                sh 'echo $(pwd)'

                sh 'mvn clean package -DskipTests '
            }
        }
        stage('Publish to dockerhub') {
            steps {
                //sh 'cd $projectDir'
                sh 'echo $(pwd)'

                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'mowa_docker_hub') {
                        def appDockerfile = 'app.Dockerfile'

                        def customImage =  docker.build('soportemowa/mes_be_service', "-f ${appDockerfile} .")

            /* Push the container to the custom Registry */
                        customImage.push()
                    }
                }
            }
        }
    }
}
