node {

	stage('Publish to dockerhub'){
    checkout scm

    docker.withRegistry('https://registry.hub.docker.com', 'mowa_docker_hub') {

    	def appDockerfile = 'app.Dockerfile'

        def customImage =  docker.build("soportemowa/mes_be_service","-f ${appDockerfile} .")

        /* Push the container to the custom Registry */
        customImage.push()
    }
    }
}